# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='currency',
            field=models.CharField(choices=[('PHP', 'Phil. Peso'), ('THB', 'Thai Baht'), ('EUR', 'Euro'), ('USD', 'Dollar'), ('CHF', 'Franken')], max_length=3),
        ),
    ]
