# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20170126_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='curr_out',
            field=models.CharField(choices=[('PHP', 'Phil. Peso'), ('THB', 'Thai Baht'), ('EUR', 'Euro'), ('USD', 'Dollar'), ('CHF', 'Franken')], default='CHF', max_length=3),
        ),
        migrations.AlterField(
            model_name='entry',
            name='currency',
            field=models.CharField(choices=[('PHP', 'Phil. Peso'), ('THB', 'Thai Baht'), ('EUR', 'Euro'), ('USD', 'Dollar'), ('CHF', 'Franken')], default='PHP', max_length=3),
        ),
    ]
